version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      
    steps:
      - checkout
      
      - run: make && make test
      
      - store_artifacts:
          path: /tmp/bin/pcx2msx
